### PR TITLE
Hello-word

### PR DESCRIPTION
**Pull request by 3rik77**
Cómo funcionaría

### CODE REVIEW

**Comment by 3rik77** [comment]
Compilación

**Comment by wader** [comment]
Hello! pushed wrong branch?

**Comment by diddledan** [comment]
@wader this looks like a spammer. They filed a similar seemingly empty PR to snapcrafters/ffmpeg#57

**Comment by wader** [comment]
@diddledan aha thanks, any idea what the point is? i don't ever understad what to click to get scammed? :) some kind of way to get false participation stats etc?

**Comment by diddledan** [comment]
no, I have no idea what they are trying to achieve. It's certainly odd behaviour. I've reported their account to GitHub.

**Comment by wader** [comment]
@diddledan 👍

**Pull request closed without merging**
