### PR TITLE
Add libsvtvp9

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
TODO: add version to json and to readme, bump config to follow master?

**Comment by wader** [comment]
- https://github.com/OpenVisualCloud/SVT-VP9/issues/159

**Comment by pyldin601** [comment]
Maybe use `libvpx` instead (or as fallback?) 🤔

**Comment by wader** [comment]
@pyldin601 hey! yeap, after some digging in https://github.com/wader/static-ffmpeg/issues/301 i came to the same conclusion and maybe understabably intel do not seem to care about arm or generic c for libsvtp9 :) let's close this one.

**Pull request closed without merging**
