### PR TITLE
Readme additions and corrections and sort libraries

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
Yeap i moved the versions.json generate after the last build now. Ah you mean use modverison even for packages that are built? yeah could make sense, maybe do in separate PR.

**Comment by wader** [comment]
@mathieu-aubin maybe you missed the diff, github has a feature that is collapses big diffs (like for Dockerfile in this case) which is a bit confusing at times

**Comment by mathieu-aubin** [comment]
i actually am on the road and didnt have time to do much more than write a comment

**Comment by wader** [comment]
Aha no stress! have a good trip

**Pull request merged**
