### PR TITLE
enables grayfilters

### PR DESCRIPTION
**Pull request by mathieu-aubin**

### CODE REVIEW

**Comment by wader** [comment]
Hi, thanks for the PR. This should only affect things if the gray codec flag is enabled right? should impact performance/output etc if not enabled?

**Comment by wader** [comment]
Trying to understand how the codec flag is used in ffmpeg. Looking at the code only some parts seems to condition the use of codec flag on CONFIG_GRAY.

Tried `ffmpeg -f lavfi -i testsrc -flags:v gray -c:v mpeg2video -t 5s test.mp4` with a ffmpeg version without --enable-gray it seems to produce gray output, confused :)

Just want to be sure enable it will not break something

**Comment by mathieu-aubin** [comment]
short of explaining as much as it would be required for a proper answer... check this JVS static releases from https://www.johnvansickle.com/ffmpeg/ 

includes/enables the filter at config time and doesnt have any negative effects.

`\ffmpeg -version | xargs -n1 echo | grep -E '(en|dis)able\-.+' | sort`

This filter, if i am not mistaken, acts on codecs config options to enable some gray specialties that go deeper in terms of settings for grayscale applications. Of course you can output grayscale without it, just maybe what comes basically set per codec, without any *possible* in depth processing

i hope this makes sense even if its not so much a definitive answer

**Comment by wader** [comment]
Yes thanks!

**Comment by wader** [comment]
Let me know if you want me to do a tagged release otherwise latest tag should be done building in a hour or so

**Pull request merged**
