### PR TITLE
fixes uavs3d bit_depth to be able to build on other platforms

### PR DESCRIPTION
**Pull request by mathieu-aubin**
ref to #94

### CODE REVIEW

**Comment by wader** [comment]
Maybe do something similar to what @pldin601 did for vid.stab, do it conditionally somehow?

**Comment by mathieu-aubin** [comment]
bit_depth 10 was and is way overkill for most stuff i've came to realize

**Comment by wader** [comment]
Ok with me. But maybe just remove the whole line instead of comment out? or add an additional comment what the lines would do?

**Comment by wader** [comment]
Thanks!

**Pull request merged**
