### PR TITLE
Adds libopencore-amr to static build

### PR DESCRIPTION
**Pull request by mathieu-aubin**
maybe check bump command...

### CODE REVIEW

**Comment by wader** [comment]
Hey, thanks. ffmpeg configure seems to fail with:
```
libopencore_amrnb is version3 and --enable-version3 is not specified
```

**Comment by wader** [comment]
bump pipeline seems to work fine:
```
$ bump pipeline 'fetch:https://sourceforge.net/projects/opencore-amr/files/opencore-amr/|/opencore-amr-([\d.]+).tar.gz/'
0.1.5
```

**Comment by mathieu-aubin** [comment]
fixed stuff, should be okay now

**Comment by wader** [comment]
👍

**Pull request merged**
