### PR TITLE
fixes vmaf issue by adding to pkg-config file

### PR DESCRIPTION
**Pull request by mathieu-aubin**

### CODE REVIEW

**Comment by wader** [comment]
Nice, how did you notice?

**Comment by wader** [comment]
Strange, master ci build fails (because checkelf "Resolve at startup: no") with this commit but the PR build succeeded 😕 any ideas? will have a look at it tomorrow

https://github.com/wader/static-ffmpeg/runs/4051902532?check_suite_focus=true
```
 > [builder 39/39] RUN   /checkelf /usr/local/bin/ffmpeg &&   /checkelf /usr/local/bin/ffprobe &&   /checkelf /usr/local/bin/qt-faststart:
#49 0.089 /usr/local/bin/ffmpeg: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, stripped
#49 0.089 No external libs: yes
#49 0.089 Relocate read-only: yes
#49 0.090 Resolve at startup: no
#49 0.090 Position independent code: yes
#49 0.090 Stack non-executable: yes
------
Dockerfile:604
--------------------
 603 |     COPY checkelf /
 604 | >>> RUN \
 605 | >>>   /checkelf /usr/local/bin/ffmpeg && \
 606 | >>>   /checkelf /usr/local/bin/ffprobe && \
 607 | >>>   /checkelf /usr/local/bin/qt-faststart
 608 |     
--------------------
error: failed to solve: process "/bin/sh -c /checkelf /usr/local/bin/ffmpeg &&   /checkelf /usr/local/bin/ffprobe &&   /checkelf /usr/local/bin/qt-faststart" did not complete successfully: exit code: 1
Error: buildx failed with: error: failed to solve: process "/bin/sh -c /checkelf /usr/local/bin/ffmpeg &&   /checkelf /usr/local/bin/ffprobe &&   /checkelf /usr/local/bin/qt-faststart" did not complete successfully: exit code: 1
```

**Comment by mathieu-aubin** [comment]
> Nice, how did you notice?

I just followed what you had already done, instead of adding the code to ffmpeg configure, it's being added from vmaf pkg-config attributes instead.

As far as this error, i honestly have no clue. I don't have the issue with the BIND_NOW when building from here (on 2 different hosts - fedora34 and centos7. It is curious

**Comment by wader** [comment]
Ok, and now master built fine, confusing. Will keep an eye on this.

**Comment by mathieu-aubin** [comment]
The error to solve issue we saw a while back come from a lack of ram i believe.
At least it happens to me when i set low ram on buile and dissapears when using adequate amount.

builder was either very depressed or victim of a holdup that time, who know.

felt like sharing - no reply needed

**Pull request merged**
