### PR TITLE
Remove hyphen from cd to support ffmpeg snapshot builds

### PR DESCRIPTION
**Pull request by timhovius**
I want to build a ffmpeg snapshot version which I downloaded from https://www.ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2

When I build this version (with a custom build argument), I get this error: 

```
cd: ffmpeg-*: No such file or director
```

This error occurs because the ffmpeg folder in this archive does not contain a version.

### CODE REVIEW

**Comment by wader** [comment]
👍 ah so you building using `--build-arg FFMPEG_VERSION=snapsnot... --build-arg=FFMPEG_SHA256=...`? funny i didn't even think about using the `ARG`:s like that :) was mostly for templating later. Maybe should even be documented as ways to do custom builds 🤔

**Comment by timhovius** [comment]
> 👍 ah so you building using `--build-arg FFMPEG_VERSION=snapsnot... --build-arg=FFMPEG_SHA256=...`? funny i didn't even think about using the `ARG`:s like that :) was mostly for templating later. Maybe should even be documented as ways to do custom builds 🤔

Yes I use this build command right now:

```bash
docker build --build-arg FFMPEG_URL=https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 --build-arg FFMPEG_SHA256=9c45167e381aef5a5735c7d4ebd779ed9a2fc28de0ec2c1acfde10719c6fb86d --build-arg ALPINE_VERSION=custom-alpine -t ffmpeg-static
```

**Comment by wader** [comment]
> FYI the newest FFmpeg version has a native xHE-AAC decoder out of the box 🥳

Yeap! have tried it? seems it still is lack some parts of xhe? ...wonder if there is plans for an encoder also, which i guess is a quite large undertaking.

**Comment by timhovius** [comment]
> > FYI the newest FFmpeg version has a native xHE-AAC decoder out of the box 🥳
> 
> Yeap! have tried it? seems it still is lack some parts of xhe? ...wonder if there is plans for an encoder also, which i guess is a quite large undertaking.

Yes I tried it with some files from the internet, and it works pretty decent.

**Pull request merged**
