### PR TITLE
Update libmysofa to 1.3 from 1.2.1

### PR DESCRIPTION
**Pull request by wader**
[Release](https://github.com/hoene/libmysofa/releases/tag/1.3)  
[Source diff 1.2.1..1.3](https://github.com/hoene/libmysofa/compare/v1.2.1..v1.3)

### CODE REVIEW

**Comment by wader** [comment]
Fails on this https://github.com/hoene/libmysofa/issues/191

**Comment by ThreeDeeJay** [comment]
After https://github.com/hoene/libmysofa/commit/dcd2e52cd49299e14df0c9bf6db71836f31bb405, libmysofa builds successfully on appveyor, though I'm not sure it'd help with github CI

**Comment by wader** [comment]
@ThreeDeeJay Aha is that a Windows build? I think https://github.com/hoene/libmysofa/commit/7aa1a10277e79642fe900552825b5e37f4fb6425 should fix it linux and others. Was hoping for a new minor release soonish but maybe it will take time?

**Comment by ThreeDeeJay** [comment]
yup, it's for the Windows build
and that's probably a question for [hoene](https://github.com/hoene) because it depends on what plans he has for the new tagged release

**Comment by wader** [comment]
Ok! i comment in https://github.com/hoene/libmysofa/issues/191 about possible new minor release, so lets see

**Comment by wader** [comment]
Replaced by #254

**Pull request closed without merging**
