### PR TITLE
Create workflow for building multiarch image on spot instances

### PR DESCRIPTION
**Pull request by pldin601**
To run this workflow the following secrets should be defined:

To spawn instances on the AWS infrastructure:
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY

To push resulting images to the docker hub:
* DOCKERHUB_USERNAME
* DOCKERHUB_TOKEN

Refs: #158 #94

### CODE REVIEW

**Comment by pldin601** [comment]
> You'r using this right now in your fork? if so maybe run it for a while and see how it behaves and then figure what to do? 

Yes. I use it to build multi arch images in my fork (https://hub.docker.com/repository/docker/pldin601/static-ffmpeg). Sure, we can test, I just need sometimes to merge upstream and trigger new build.

> What do the hashes in `.terraform.lock.hcl` refer to? 

It caches exact versions of dependencies (providers and modules) used in terraform configuration. It's like package-lock.json in NPM. (for details, see https://www.terraform.io/language/files/dependency-lock)

When terraform creates resources on the AWS, it saves the state to a different state file. This file is cached inside the workflow file and used then to destroy all created resources after build has been finished (successfully or with error).

**Comment by wader** [comment]
Ok thanks!

**Comment by pldin601** [comment]
@wader Did you manage to test this workflow on your own?

**Comment by wader** [comment]
@pldin601 No haven't tried it myself yet :( good you pinged me. I should really get a AWS account set this up. Maybe start by running it in parallell to the github action build and push to a test image and then switch over to only this?

btw is the tag config https://github.com/wader/static-ffmpeg/blob/master/.github/workflows/ci.yml#L33 different with this? currently master branch will be pushed as latest and tags as just same tag

**Comment by pldin601** [comment]
In my PR, I use my own logic for generating tags, but it can be tuned for sure.

**Comment by wader** [comment]
Okok, had a closer look now. So if understand it correctly the action atm is triggered manually (workflow_dispatch) and will push to tag $DATE-$SHORT_DIGEST_OF_HEAD?

**Comment by pldin601** [comment]
@wader Kinda.

**Comment by wader** [comment]
Aha think i want to keep the current tag behaviour so that have to be tuned somehow. As we don't push multiple tags for one push/tag it feels like it shouldn't be that much to change? change even to `on push` and somehow mangle master ref into "latest" and tag name can be just as is.

Wonder if pull request builds would still be done with github actions or not? but would be nice to build the same way concidering the breakages we have seen before... but think it will be much less of an issue when not emulated.

btw when building using this i assume the full build log will end up in the github action log?

**Comment by pldin601** [comment]
I think it would be too expensive to trigger builds on spots on each push. Because AWS has some quotas on spot requests API. I'd suggest using it only when pushing it to master, or even by triggering it manually.

Full build log will be piped to the GitHub action log https://github.com/myownradio/static-ffmpeg/runs/5853072062?check_suite_focus=true#step:4:25

**Comment by wader** [comment]
> I think it would be too expensive to trigger builds on spots on each push. Because AWS has some quotas on spot requests API. I'd suggest using it only when pushing it to master, or even by triggering it manually.

Yes good point. So maybe something like this:

- PRs -> Github action
- master -> AWS and push to latest
- tag -> AWS and push to same tag name

And keep a workflow_dispatch thingy around just in case.

I think what i mostly want avoid is to have tag builds fail for some reasons that could have been known.

A bit focused on other things atm, want to finish up a new [fq](https://github.com/wader/fq) release, so not sure when i will look into the changes needed. Let me know if you start working on it.
 
> Full build log will be piped to the GitHub action log https://github.com/myownradio/static-ffmpeg/runs/5853072062?check_suite_focus=true#step:4:25

👍

**Comment by wader** [comment]
> I had no chance to look into because was focused on another work.

No worries, same for me

> Now, I'm thinking about moving this workflow into a reusable workflow file. Because I have a few projects, what is going to be multi-arch, and I don't want to maintain a few copies of the same thing.
> 
> It can be used like this: https://github.com/pldin601/torrent-bot/blob/master/.github/workflows/build-multiarch.yml
> 
> So, you can maintain your own logic of defining the image tag and pass it to the job. I just have a few things to do before finishing.

Very nice! will have a poke around. Any plan of branch->tag mapping?

I've thought about if it would be possible to have some kind of generic docker aws "bridge" action. I guess more or less what you're doing now and move the docker command to be an argument or somehow have a "shim" docker script that and use `run:` and forward env/secrets etc? but it was a while since i messed around any deep with github actions so i might be just mumbling :)

**Comment by pldin601** [comment]
> Very nice! will have a poke around. Any plan of branch->tag mapping?

The `branch->tag` logic can be defined outside the build workflow. It can be mapped anyhow.

> I've thought about if it would be possible to have some kind of generic docker aws "bridge" action. I guess more or less what you're doing now and move the docker command to be an argument or somehow have a "shim" docker script that and use `run:` and forward env/secrets etc? 

Not sure if I understand the idea. Do you mean the making of some magic action, that spawn instances, do some work and destroy the instance after all?

**Comment by wader** [comment]
> The `branch->tag` logic can be defined outside the build workflow. It can be mapped anyhow.

Aha you just do `docker tag user/repo:$DOCKER_IMAGE_TAG user/repo:1.2.2` or whatever you want after the aws build/push step?

> Not sure if I understand the idea. Do you mean the making of some magic action, that spawn instances, do some work and destroy the instance after all?

Yes something like that, but now based on the thing you said above i think that makes much more sense to do. I guess to do what i was mumbling about you would probably have to keep the aws instance between steps somehow

**Comment by pldin601** [comment]
> Aha you just do `docker tag user/repo:$DOCKER_IMAGE_TAG user/repo:1.2.2` or whatever you want after the aws build/push step?

The short answer is yes. But, in details, I build two separate images on each architecture and push them separately to the docker hub with the different tag (by appending the tag with the arch suffix). Then I have to use one of the spawned machines to "merge" those images into a single multi-arch image with the **docker manifest** command.

Problem here is that the docker manifest after mergin does not clean up source tags and there are some garbage will remain in the docker hub until it will be removed by hands. Probably, we could perform some API call from the workflow to remove those tags after running manifest.

> Yes something like that, but now based on the thing you said above i think that makes much more sense to do. I guess to do what i was mumbling about you would probably have to keep the aws instance between steps somehow

It can be done with the "matrix" (https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) I guess. But it looks like an idea for different workflow. For building something very specific. For example, gstreamer...

**Comment by wader** [comment]
@pldin601 Poking around with aws. Guess i should add a restriced user with only EC2 access etc and add a key for it? currently my aws account is waiting to be "fully activate", something else i should do?

**Comment by pldin601** [comment]
> @pldin601 Poking around with aws. Guess i should add a restriced user with only EC2 access etc and add a key for it? currently my aws account is waiting to be "fully activate", something else i should do?

Ideally, you have to generate credentials only for spawning spots and making ssh keys. You also have to generate the token for docker hub.

**Comment by wader** [comment]
Hey,  now there are  AWS_* action secrets for a user with a policy from https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html that i hope should be enough. The AWS IAM and policy stuff is quite confusing and so many things.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowLaunchInstances",
            "Effect": "Allow",
            "Action": [
                "ec2:RunInstances"
            ],
            "Resource": [
                "arn:aws:ec2:us-east-1::image/*",
                "arn:aws:ec2:us-east-1:*:subnet/*",
                "arn:aws:ec2:us-east-1:*:network-interface/*",
                "arn:aws:ec2:us-east-1:*:security-group/*",
                "arn:aws:ec2:us-east-1:*:key-pair/*",
                "arn:aws:ec2:us-east-1:*:volume/*",
                "arn:aws:ec2:us-east-1:*:instance/*",
                "arn:aws:ec2:us-east-1:*:spot-instances-request/*"
            ]
        },
        {
            "Sid": "TagSpotInstanceRequests",
            "Effect": "Allow",
            "Action": "ec2:CreateTags",
            "Resource": "*"
        }
    ]
}
```
Looks ok?

Some other questions:

The github repo is not the same as the docker hub image name (sadly). Should be enough to set `DOCKER_IMAGE_NAME` to `mwader/static-ffmpeg`?

For testing should we prefix the tag somehow or just run with `DOCKER_IMAGE_NAME` set to `mwader/static-ffmpeg-multi-test` etc?

**Comment by pldin601** [comment]
To be honest, I'm not strong in AWS policies, but it looks a bit wrong. You need to grant permission to perform these actions at least:

- [RequestSpotInstances](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotInstances.html)
- [CancelSpotInstanceRequests](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CancelSpotInstanceRequests.html)

Also, there should be something related to SSH Keys. You can find the detains here: https://docs.aws.amazon.com/service-authorization/latest/reference/list_identityandaccessmanagement.html#identityandaccessmanagement-actions-as-permissions

Regarding the `DOCKER_IMAGE_NAME` - yes, we can override the image name. And it's better to test with the prefix for now.

**Comment by wader** [comment]
> To be honest, I'm not strong in AWS policies, but it looks a bit wrong. You need to grant permission to perform these **Actions** at least:
>  ...

Thanks, will have a look later. It's the first time i mess around with AWS IAM things so i have no idea what i'm doing :) but we will get there

> Regarding the `DOCKER_IMAGE_NAME` - yes, we can override the image name. And it's better to test with the prefix for now.

👍  thinking maybe i will create a separate test repo to be able to debug iterate faster

**Pull request merged**
