### PR TITLE
Update cargo-c-rust from 1.56.0 to 1.57.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
Seems 1.57 image was changed:
```
-#8 [cargo-c 1/5] FROM docker.io/library/rust:1.57.0-bullseye@sha256:bfe6d0a46a26e0f4fe9ca1b964488e1fbb1846f1590b4002021135512aeb37ff
+#8 [cargo-c 1/5] FROM docker.io/library/rust:1.57.0-bullseye@sha256:2ac0f07e53346494cc5f7541b470adf7a7c06caf64417494dd5695ad9bc65e83
```
hmm

**Comment by mathieu-aubin** [comment]
i noticed tht lasr version of alpine has rust 1.56 - Could we do without this "hack" now by using distro specific version?

**Comment by wader** [comment]
Good point, i think so. Wonder if that is part of the reason why cargo-c is still stuck in edge testing?

**Comment by wader** [comment]
Worked fine https://github.com/wader/static-ffmpeg/pull/141, nice to get rid of that hack 👍  thanks

**Pull request merged**
