### PR TITLE
twasss ugly, now looks better

### PR DESCRIPTION
**Pull request by mathieu-aubin**

### CODE REVIEW

**Comment by mathieu-aubin** [comment]
comments would add to the purpose and maybe help other navigate thru all this. but... not needed.

**Comment by wader** [comment]
Good idea to format. I usually format with vscode shell-format, it seems to not indent like this but i mostly just want consistency in the same file, so ok to merge with me.

You mean comments about the different arch cases or why the script exist or do?

**Comment by mathieu-aubin** [comment]
just basic commenting about why this file exist in the first place. standlone, it had no meaning... comments make it meaningful even when taken  alone. if that makes sense

**Comment by wader** [comment]
https://github.com/wader/static-ffmpeg/pull/130

**Pull request merged**
