### PR TITLE
increases uavs3d bit depth to 10

### PR DESCRIPTION
**Pull request by mathieu-aubin**

### CODE REVIEW

**Comment by wader** [comment]
Dont know much about uavs3d, how will this affect the encoder/decoder? Any referenses about it that could be a comment etc?

**Comment by mathieu-aubin** [comment]
Well... if it was encoding, as per the following:

> The higher quality of 10-bit video also means the files it creates are comparatively larger than 8-bit videos, so they take up more space in storage and more processing power when editing. The extra quality can be worth it, but only if it’s required in your workflow.

then i would probably say that it's not worth it. But since it's a decoder only here, having the 10bit capability for avs3 should be a good thing. I wish i was less french and had a better answer for you

Ultimately, it is ypuor call

**Comment by wader** [comment]
Sorry if i i sounded harsh, now i have checked the source or readme of the project. I didn't understand that it was something officially supported by uavs3d.

Thanks! do you have first hand experience with avs3? i haven't used it myself, common on asia?

**Comment by mathieu-aubin** [comment]
You didn't sound harsh or anything.
Don't worry brother, we both want this project to evolve positively.
Maybe my reply saying it was yur call made it sound like i was offended or something... thats not the case. It was just a fact and if i was to have issues with you asking questions, i could just do my own stuff alone - right?

I don't have tons of experience with any or theses, really. AVS3 is way out of my league in terms of media capture prices and so on. Just want a good tool that can do it all while perfecting some shadow skills.

Je suis Quebecois, not asian if thats what you meant heheh

**Comment by wader** [comment]
> You didn't sound harsh or anything. Don't worry brother, we both want this project to evolve positively. Maybe my reply saying it was yur call made it sound like i was offended or something... thats not the case. It was just a fact and if i was to have issues with you asking questions, i could just do my own stuff alone - right?

Great! yeap exactly the same for me, i'm very interested in media technology and ended doing this project when most of the ffmpeg builds were hard to use or lacked some features when workin on other hobby projects (mostly https://github.com/wader/ydls) and work stuff.

Really appreciable you helping out! let me know if you want me to add you as a collaborator if that would make things easier.

> I don't have tons of experience with any or theses, really. AVS3 is way out of my league in terms of media capture prices and so on. Just want a good tool that can do it all while perfecting some shadow skills.
> 
> Je suis Quebecois, not asian if thats what you meant heheh

Ah nono just read about AVS3 and that is seems to be a chinese initiative :)

**Pull request merged**
