### PR TITLE
WIP: librtmp integration

### PR DESCRIPTION
**Pull request by mathieu-aubin**

### CODE REVIEW

**Comment by mathieu-aubin** [comment]
i build on another server and commit on my own computer... missed the ARG while recopying

**Comment by wader** [comment]
Not sure what is going on with this build failure, alpine weirdness?

**Comment by mathieu-aubin** [comment]
problem comes from incompatibility with openssl 1.1+

**Comment by wader** [comment]
Maybe can get some clues from https://git.alpinelinux.org/aports/tree/main/rtmpdump?h=master but seems they link with gnutls hmm

**Comment by mathieu-aubin** [comment]
This is polluting as of now and i can't have it work yet so i'm closing

**Pull request closed without merging**
