### PR TITLE
Update uavs3d from 57d20183301d4197d1c938f62f8a5911e33465d7 to 073fe7cc8eaef021aa4adc7b0100461e0260b70d

### PR DESCRIPTION
**Pull request by wader**
[Source diff 57d20183301d4197d1c938f62f8a5911e33465d7..073fe7cc8eaef021aa4adc7b0100461e0260b70d](https://github.com/uavs3/uavs3d/compare/57d20183301d4197d1c938f62f8a5911e33465d7..073fe7cc8eaef021aa4adc7b0100461e0260b70d)

### CODE REVIEW

**Comment by wader** [comment]
@mathieu-aubin  👀

**Comment by mathieu-aubin** [comment]
is this because i''ve told the uavs3d team to stop using gawk and use awk instead as it is more popular and in most systems?

**Comment by wader** [comment]
Yeap i checked the diff link a noticed your name :)

Aha i didnt notice the commit hash was empty, not good. Ill fix.

**Comment by mathieu-aubin** [comment]
btw, bump is a great thing. i whish i had more time to grasp it fully (even tho it looks simple enough...). Thanks for you dedication, also.

**Comment by wader** [comment]
Thanks :) yeah it has turned out well, i use it for most of my open source projects now and also some at work. Now when i used it a while i have some ideas how i actually should have done it of course, will see, it works quite well as-is also.

**Comment by mathieu-aubin** [comment]
There's always room for improvement i figure. As long as you don't fall into every rabbit holes... it'll be decent as a tool and for your mind!

**Pull request merged**
