### PR TITLE
Update alpine from 3.12.2 to 3.12.3

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by Gounlaf** [comment]
@wader any reason you just don't use `alpine:3.12` ?
patch version should not break anything... (ok, PR with libsrt is proving it but anyway :sweat_smile:)

**Comment by wader** [comment]
It is mostly to get as deterministic builds as possible, and with the bump version update automation I get both very specific (latest) version and quite deterministic builds.  Also as you noticed with libsrt it's a good way to detects build issue early.

Has is caused any issue for you?

**Comment by Gounlaf** [comment]
> Has is caused any issue for you?

Not at all! I was just wondering why... and your answer it's perfectly clear :)

Thanks!

**Comment by wader** [comment]
👍

**Pull request merged**
