### PR TITLE
added image for 4.2.2 with srt enabled

### PR DESCRIPTION
**Pull request by eflynn-istream**

### CODE REVIEW

**Comment by wader** [comment]
Hello! just curious, was there some issue with 4.3.1 with srt enabled?

**Comment by eflynn-istream** [comment]
We are using a custom JS player and for some reason our player doesn't like the newer version of ffmpeg >=4.30, so we are trying to stick to 4.2.2 but enable SRT.
________________________________

**Comment by wader** [comment]
Aha! thanks for the answer

**Comment by eflynn-istream** [comment]
> Aha! thanks for the answer

No problem! I actually just sent an email to your gmail account listed regarding this PR if you have a moment to take a look.

**Pull request closed without merging**
