### PR TITLE
Build multi-arch images on AWS spot instances

### PR DESCRIPTION
**Pull request by pldin601**

### CODE REVIEW

**Comment by wader** [comment]
As this is quite generic one idea could be to have this as a separate repo that is reusable by other builds? other repos could trigger it to build by using https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch for example? just thinking out loud 🤔

Btw do you have any idea roughly what a spot instance static-ffmpeg build costs? good to have clue what kind of money it is :)

**Comment by pldin601** [comment]
@wader It costed to me around $0.07 to build the arm64 image yesterday.

**Comment by mathieu-aubin** [comment]
maybe, just maybe, could different arches be set on different --blank-- ?

insert branch, repo, project or whatever here.

I think, maybe i think, that a universal solution complicates things to a point where it discourages MANY from participating to the project, as in... "well i had thjs thing working but cant have it aprooved only if i can invest time into something i could careless, moving on to other shit!"

I hope you understand my idea here and that i have proven to be of help mor3 than a nuisance here which, altho irrelevant in the discussion, could give some weight to such (my) statement in the realm of at least being entertained and a shit be attributed. Geee i love when i get brain farts like theses.

Thanks and as many my exes said, keep it up!

**Comment by mathieu-aubin** [comment]
Re-reading...

another --blank-- would allow for more seamless resolution of disparitions between advancements with regards to feasability and issues pertaining to having over complicated hacks that are, well, worth whatever to whomever (irrelavant) and for which opinions greatly vary. It could cause impediments into the whole with regards to advancements and block even the tiniest relevant and positive 'milestone' or better said, achievement of progress

**Comment by wader** [comment]
@mathieu-aubin No worries and i much appreciative your contributions, ideas and attitude! I think i understand what you mean and i too really wish to keep things as simple as possible and that the Dockerfile should be usable with just a `docker build .`. I think most of headaches we have seen has been because docker:s leaky emulation, if it was native hosts i think things would just-work much more.

But i guess it's a bit of a balance, having just one multi-arch image would be quite neat also and very clean and simple for users of the image. So in summary for me i think it's a good idea be allow hacky things inside the Dockerfile to do whatever is needed to produce static binaries but be cautious with complicated things in CI and build env etc?

> Thanks and as many my exes said, keep it up!

Same! 😁

**Comment by wader** [comment]
> @wader It costed to me around $0.07 to build the arm64 image yesterday.

👍  thanks for testing, ill buy you a beer if we ever end at the same conference! so one beer is like 70 static-ffmpeg builds :)

**Pull request closed without merging**
