### PR TITLE
Add qt-faststart

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
Have no decided if should include for not. Same thing can be done with mov faststart options i think

**Comment by mathieu-aubin** [comment]
true about the movflags +faststart but there is some risk of butchering some other metadata, or so i understand from reading more about it. One would also need to add `-map_metadata 0` to make sure this doesnt happen.

I dont know how much harder this would be but i still think that qt-faststart is a nice addition.

**Comment by wader** [comment]
Ok! good points. I've fixed the conflict and will merge once the ci system is happy.

**Comment by mathieu-aubin** [comment]
oh, i guess i did not realized there was also a branch already created. good stuff. thank you for considering  people's input and keep it up!

**Pull request merged**
